"""create table influence_zones

Revision ID: 014c8c3a6256
Revises: 788b98aa658a
Create Date: 2026-07-13 02:23:20.304692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014c8c3a6256'
down_revision: Union[str, Sequence[str], None] = '788b98aa658a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influence_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earthquake_id', sa.Integer(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['earthquake_id'], ['earthquakes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('earthquake_id')
    )
    op.create_index(op.f('ix_influence_zones_id'), 'influence_zones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_influence_zones_id'), table_name='influence_zones')
    op.drop_table('influence_zones')
    # ### end Alembic commands ###
