"""init seismic system

Revision ID: 2444b6fe8428
Revises: 
Create Date: 2026-06-14 10:31:30.607941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2444b6fe8428'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seismic_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earthquake_id', sa.Integer(), nullable=True),
    sa.Column('log_n', sa.Float(), nullable=True),
    sa.Column('log_t', sa.Float(), nullable=True),
    sa.Column('log_r', sa.Float(), nullable=True),
    sa.Column('dm', sa.Float(), nullable=True),
    sa.Column('prediction', sa.String(length=20), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['earthquake_id'], ['earthquakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seismic_analysis_id'), 'seismic_analysis', ['id'], unique=False)
    op.create_table('seismic_cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['earthquakes.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['earthquakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seismic_cluster_id'), 'seismic_cluster', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seismic_cluster_id'), table_name='seismic_cluster')
    op.drop_table('seismic_cluster')
    op.drop_index(op.f('ix_seismic_analysis_id'), table_name='seismic_analysis')
    op.drop_table('seismic_analysis')
    # ### end Alembic commands ###
