"""zonagps

Revision ID: 51fa6af87dc4
Revises: c1374ae759d7
Create Date: 2026-06-26 21:00:37.954092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51fa6af87dc4'
down_revision: Union[str, Sequence[str], None] = 'c1374ae759d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zona_gps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat_grid', sa.Float(), nullable=False),
    sa.Column('lon_grid', sa.Float(), nullable=False),
    sa.Column('kode_klaster', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zona_gps_id'), 'zona_gps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zona_gps_id'), table_name='zona_gps')
    op.drop_table('zona_gps')
    # ### end Alembic commands ###
