"""initial migrate

Revision ID: c1374ae759d7
Revises: 
Create Date: 2026-06-20 12:42:44.146453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1374ae759d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earthquakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('dirasakan', sa.Text(), nullable=True),
    sa.Column('wilayah', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earthquakes_event_time'), 'earthquakes', ['event_time'], unique=False)
    op.create_index(op.f('ix_earthquakes_fingerprint'), 'earthquakes', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_earthquakes_id'), 'earthquakes', ['id'], unique=False)
    op.create_index(op.f('ix_earthquakes_time'), 'earthquakes', ['time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('seismic_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earthquake_id', sa.Integer(), nullable=False),
    sa.Column('parent_earthquake_id', sa.Integer(), nullable=True),
    sa.Column('n_value', sa.Float(), nullable=True),
    sa.Column('log_n', sa.Float(), nullable=True),
    sa.Column('log_t', sa.Float(), nullable=True),
    sa.Column('log_r', sa.Float(), nullable=True),
    sa.Column('dm', sa.Float(), nullable=True),
    sa.Column('prediction', sa.String(length=20), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['earthquake_id'], ['earthquakes.id'], ),
    sa.ForeignKeyConstraint(['parent_earthquake_id'], ['earthquakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seismic_analysis_id'), 'seismic_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seismic_analysis_id'), table_name='seismic_analysis')
    op.drop_table('seismic_analysis')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_earthquakes_time'), table_name='earthquakes')
    op.drop_index(op.f('ix_earthquakes_id'), table_name='earthquakes')
    op.drop_index(op.f('ix_earthquakes_fingerprint'), table_name='earthquakes')
    op.drop_index(op.f('ix_earthquakes_event_time'), table_name='earthquakes')
    op.drop_table('earthquakes')
    # ### end Alembic commands ###
